spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080

#mp日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    开启驼峰自动转化
    map-underscore-to-camel-case: true

files:
  upload:
    path: C:\IdeaProjects\springboot学习\schoolspringboot\src\main\resources\static\upload\

